### ISSUE TITLE
Allow events to choose speakers anonymously 

### ISSUE THREAD

**Issue by renatooliveira** [luanfonceca/speakerfight#139]
Would be awesome to have the possibility of choosing the speakers of your conference anonymously. 

Thinking here, would be a choice field, and then when the organizers are choosing they can choose without any bias (i.e known speakers)

Also, I'm willing to do this feature

**Comment by fjsj** [comment]
+1
this was suggested at PyNE 2016 by @berinhard too.

what do you think @luanfonceca?
I can help to implement this too!

**Comment by berinhard** [comment]
@fjsj I'm thinking about start a branch for this issue by this week. If I do so, I'll notify you here if you want to help.

**Comment by mauricioabreu** [comment]
@renatooliveira I did not follow you here.

What does mean "choose speakers anonymously"? Does the app show which organizer choose the speakers?

**Comment by berinhard** [comment]
@mauricioabreu nowadays with Speakerfight, the talks of an event are always show with the picture and the name of the speaker. This information could lead the voters to measure their vote based on *who* will talk and not on *what* will be talked. What @renatooliveira is suggesting is to add a feature were the owner of the event can say that, for his/her event, the speaker info shouldn't appear, only the talk content itself.

This is important because, without it, we're very suggested to keep having the same speakers through the events and this is a barrier for new people to come to talk. This is also important because anonymity encourages people who belongs to minority group to feel more comfortable about submitting talks.

**Comment by mauricioabreu** [comment]
@berinhard Thanks for the explanation.
Even half agreeing with this, I can do it too.

Anyways, the owner of the project seems to be busy.
