### ISSUE TITLE
An issue to see the importance of other issues

### ISSUE THREAD

**Issue by vmesel** [luanfonceca/speakerfight#151]
As @luanfonceca is now with less time available for this project, the community will help him to maintain the project working. We need to set some priorities so we could work on more precise and more useful things first.
- CSS things should be less important?
- Should we create custom labels as on googlefonts/fontbakery? 
- Finding a sponsor for the project will help?

**Comment by mauricioabreu** [comment]
It is an open source project and a product/service. Everything is important. 
Of course some issues are more important than others (like bugs) but it is not related to the technology.

What we need here is people with permission to push to the project (collaborators). I have a good knowledge of the project and codebase, but stopped to contribute because pull requests were not being handled for the reasons @luanfonceca mentioned.

**Comment by vmesel** [comment]
@mauricioabreu I know that every issue is important, but we should establish a priority to them, so we can work on the more critical ones! Another thing, why don't you start a fork on the projects base so we can work on the changes and get everything done without needing to return them to the main repo?

Obviously it is going to create to separate projects, but it's like giving continuity for a project that is "dead".

**Comment by mauricioabreu** [comment]
Because forks are made for two reasons:
* Maintainers decided to leave the project
* For private reasons like bugfix
Not the case here. It is a product and has a name outside (http://speakerfight.com/)

As a contributor that believes on this main repository, no, I will not fork it.

**Comment by luanfonceca** [comment]
Hi @vmesel, i am now working in @labcodes so i am working in Speakerfight part-time every month, so we create two new milestones, one that will end on December and the other on March.

So the project are running again, sorry if its too late.
