### ISSUE TITLE
Voting system should be simplified and should show some some statistics

### ISSUE THREAD

**Issue by vmesel** [luanfonceca/speakerfight#154]
Hey guys,
As I'm an event organizer, I would like to see what people think about the talks that were submitted in speaker fight. The voting system nowadays is very simple and does not show how is a speak feedback. 

A suggestion would be to shrink it to 3 different options like (Great - Regular - Didn't Like it) so people can express better their opinions.

Another thing that we could do to help organizers is giving a graphic visualization of this voting answers, so we could see the performance of a speak and things like this. What do you think?

**Comment by luanfonceca** [comment]
Today we have three kinds of Voting systems:
1. Public Voting (Everyone can vote on any proposal once)
2. Jury Voting (Jus the Jury selected by the organizer can vote on proposals)
3. Anonymous Voting (In the proposal's list we hide all information about the speaker)

I would like to offer more alternatives, if someone wants to use this instead of the #1 i think it is nice to be done.

o/

**Comment by luanfonceca** [comment]
I am closing this issue now, ok?
