### ISSUE TITLE
Remove login from Facebook, Gmail and Email.

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#36]
As our target customers are all programmers, we need simplifies the process of login, allow just for Github.

And this will destroy the dependency of a email-system reminding people of they password and the multiple account problem (Where people with different email make login multiples times.).

**Comment by jonatasoliveira** [comment]
Any thoughts about what to do with the login of people that already logged in using one of these authentication providers?

**Comment by luanfonceca** [comment]
Hi @jonatasoliveira, i do, for me the best approach:
Remove the authentication using Facebook, Google and Email.
Send an email asking to the users to login using Github (some users already have signed in with Github after have an account using the email, for example).
Migrate the old user votes to the new `User`.
Delete the old ones.

**Comment by jonatasoliveira** [comment]
Nice, @luanfonceca. There is any chance to do it automagically? Like the user login with Github and if it's the same email from another authentication we migrate the data.

**Comment by luanfonceca** [comment]
I dont know, because the user must to allow the Github to use his account.
But in the email we can add direct link Github login, so He will need just to click and accept.

**Comment by rennerocha** [comment]
Does it make sense remove login options for the system?
Why should it be required for the users to have an account in an specific closed and proprietary platform to allow them to login in the system? Even if the system has a programmer user focus, it is not mandatory that all participants of the events will be programmers too, and nor all programmers have Github accounts.

**Comment by lucasmiqueias** [comment]
I Agree, not all programmers it has github.

**Comment by luanfonceca** [comment]
There is some hard scenarios when you allow people to login with all that social networks:

1. Some people forget how social network he has been signed up, so they create unnecessary accounts.
2. Create one account for each possible authentication method to vote on his own proposal multiple times.
4. We need to offer a interface to, change password, reset password, change profile information.
5. We need to integrate accounts and take care of its multiples accounts on all the platform.

All that work consume time, that time which can be distributed to the growth of the platform, instead of being just wasted on login and signup, i don't think that this is a problem that we need to solve to make people use our application. 

And all is for discussion here.

 o/

**Comment by rennerocha** [comment]
1. Some people forget how social network he has been signed up, so they create unnecessary accounts.
These accounts will not need maintenance. Just will be stored in the database. We can even disable them after some time, and if the user tries use them again, it could require reactivate, reset password or something like that.

2. Create one account for each possible authentication method to vote on his own proposal multiple times.
If someone really wants to do something like that, he/she will do no matter how the accounts system works. You need to have some trust in the user behaviour. Besides, the event owner certainly will be following the votes and will notice if something like that happens.

3. We need to offer a interface to, change password, reset password, change profile information.
4. We need to integrate accounts and take care of its multiples accounts on all the platform.
Instead of forcing an user to have an account in Github, we can use some library that integrates that. An example is http://www.intenct.nl/projects/django-allauth/ that integrates everything, so we don't need to have to take care of multiple accounts. Integrate with OpenID is a good alternative too.

I can't see the platform growing and reaching users outside programmers world (and programmers that don't use github), if you remove from them alternatives to registering to the platform that they are accustomed to using, further existing good alternatives to handle this with not much effort.





    Some people forget how social network he has been signed up, so they create unnecessary accounts.
    Create one account for each possible authentication method to vote on his own proposal multiple times.
    We need to offer a interface to, change password, reset password, change profile information.
    We need to integrate accounts and take care of its multiples accounts on all the platform.

**Comment by luanfonceca** [comment]
Hi @rennerocha, i agreed with you on all that, i just don't agree on spent time in all that, but its okay for me.

We already use `django-allauth`. So, this process should be less painful. I am okay with the all authentication methods, but we need to apply the Speakerfight style to the pages, so i am opening a issue for each page that should exist and relate that issues with this one, for people to track this talk.

o/

**Comment by sergiovilar** [comment]
Github is currently not working, I only see this message when try to login:

```
Internal Server Error
I'm sorry, that page is currently unavailable due to a server misconfiguration. The server administrator has been notified, and we apologise for any inconvenience.

SpeakerFight é orgulhosamente um projeto open-source e esta sempre sendo melhorado. Se o software apresentar qualquer comportamento estranho por favor nos informe. ```

**Comment by luanfonceca** [comment]
I am closing this talk, through the issues #30 and #65, we are improving the UX of the '/accounts/' interface. It needs to be much better, for now "working" is good enough.

o/
