### ISSUE TITLE
Feedback for the folks!

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#49]
I thinks in this triggers for email:

1. Signup;
2. Event created;
3. Event receives a new Proposal;
2. Proposal created (The Event jury and the Proposal author receives an email);
4. Proposal receives a Vote;
5. Past week feedback for the Event author;

**Comment by berinhard** [comment]
I'm a :+1: for all of these events, except the 5 and 6. 

For example, let's imagine that a proposal receives 15 votes. If we are sending an email to the author, on every vote, he/she will receive 15 emails just saying: "oh, you have a vote for your proposal" and I don't think that this information is relevant itself. Maybe we could add a page (if it does not already exist) to the autor see the votes for his/her talks.

And for the feedback status, I think that the approach of serving a page that show this feedback to the author is better than emailing him. I mean, by definition the event author is the person who is most interested on the event. So it fair for us to assume that the author will access the Speaker Fight to see how the event is going rather than just keep waiting for emails to pop up and show him the info.

**Comment by berinhard** [comment]
Now, about the infrastructure, we need to define which mailing service we will use. I am :+1: for Mandrill.

**Comment by berinhard** [comment]
I'm starting to work on this feature at [this branch](https://github.com/berinhard/speakerfight/tree/feature/feedback-email) right now.

**Comment by luanfonceca** [comment]
Hi @berinhard, i am totally agreed with you, will be not a good idea to spam they mailbox like that. I will create an new issue for the Feedback page in the event then!

I am agree for us to use the Mandrill, they have a lots of email in the free version, so its ok for me too.

Thanks for all.
o/

**Comment by berinhard** [comment]
I'll need to do a change on the settings organization because today we have only one for testing, dev and prod purpose. For now, since we do not send any email, i'm changing Django's email backend to use memory, but I'll make another PR fixing the settings. Ok?

**Comment by luanfonceca** [comment]
Its ok for me. We have the `local_settings.py`, I normally use it for put passwords and other sensitive data.

**Comment by berinhard** [comment]
I'll split this issue in two others: 

1 - Send sign up feedback: because the way to send the email changes on how the user is created.
2 - And the structure of settings as we discussed.

**Comment by luanfonceca** [comment]
Thanks for that @berinhard 

o/
